### ISSUE TITLE
Gutenberg Times

### ISSUE THREAD

**Issue by palmiak** [dgwyer/gutenberg-development-resources#1]
I think that https://gutenbergtimes.com/ should be added to this list too.

There is no better place for developers to learn what is happening in Gutenberg right now. Also you can always download a zip of the latest Gutenberg version and Birgit's and Greg's podcast is very useful too.

**Comment by dgwyer** [comment]
Added, thanks!

**Comment by dgwyer** [comment]
Have added it to the blog and (new) podcasts sections.
